/**
* Documentation Using Swagger UI
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.whattowhere.data.remote.dto.request


/**
 * 
 * @param UserId 
 * @param Password 
 */
data class ForgotPasswordRequestModel (
    val UserId: Long,
    val Password: String
) {

}

