/**
* Documentation Using Swagger UI
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param UserName 
 * @param FirstName 
 * @param LastName 
 * @param Mobile 
 * @param Gender 
 * @param ProfileImage 
 * @param IsEmailVerified 
 * @param UserType 
 * @param Email 
 * @param Password 
 * @param LoginType 
 * @param FirebaseToken 
 * @param DeviceType 
 */
data class NewUserModel (
    val UserName: String,
    val IsEmailVerified: Boolean,
    val UserType: String,
    val Email: String,
    val Password: String,
    val LoginType: String,
    val FirebaseToken: String,
    val DeviceType: String,
    var ProfileImage:String=""

) {

}

