/**
* Documentation Using Swagger UI
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param UserId 
 * @param OldPassword 
 * @param Newpassword 
 */
data class ResetPasswordModel (
    val UserId: Long,
    val OldPassword: String,
    val Newpassword: String
) {

}

