/**
* Documentation Using Swagger UI
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param message 
 * @param issuccess 
 * @param &#x60;data&#x60; 
 */
data class ResponseModel (
    val message: String? = null,
    val issuccess: Boolean? = null,
    val `data`: Any? = null
) {

}

